cbmc-viewer: add blank line as required by brew audit (#668)
This addresses the following (new) error:
```
aws/tap/cbmc-viewer
  * line 2, col 3: Add an empty line after module inclusion.
Error: 1 problem in 1 formula detected.
Error: `brew audit` failed for cbmc-viewer!
```