cbmc-viewer: Address `brew audit` error
Addresses the following error:
```
Error: 1 problem in 1 formula detected.
  * line 62, col 5: Use `assert_path_exists <path_to_file>` instead of `assert_predicate testpath/"report/html/index.html", :exist?`
Error: `brew audit` failed for cbmc-viewer!
```